"""Add Review Model

Revision ID: 553dd6a586b7
Revises: 0baa13cd3c08
Create Date: 2023-01-02 12:06:40.540830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553dd6a586b7'
down_revision = '0baa13cd3c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
